import { Conversation, WorkbookPage, Workbook } from './types';
import { v4 as uuidv4 } from 'uuid';

/**
 * Solar System Demo Workbook content.
 * Matches the high-fidelity mock generated by mockProvider.
 */

function getMockContent(title: string, objective: string, type: string): string {
  const t = title.toLowerCase();

  // 1. Cover Page
  if (t.includes('grand design')) {
    return `
<section class="page">
  <div class="layout-f">
    <div class="f-top">
      <h1 style="font-size: 42pt; margin-top: 40mm;">${title}</h1>
      <p style="font-size: 18pt; opacity: 0.8; margin-top: 10mm;">Exploring the wonders of our cosmic neighborhood.</p>
    </div>
    <div class="f-body">
      <div class="grid-bento">
        <div class="bento-main">
          <h3>The Sun: Our Star</h3>
          <p>The Sun accounts for 99.86% of the mass in the Solar System. It is the gravitational anchor that holds everything in place.</p>
          <div class="takeaway">Without the Sun's energy, life on Earth would be impossible.</div>
        </div>
        <div class="bento-side">
          <strong>Quick Fact</strong>
          <p>Light takes about 8 minutes and 20 seconds to travel from the Sun to the Earth.</p>
        </div>
      </div>
    </div>
  </div>
</section>`.trim();
  }

  // 2. Math / Physics (KaTeX)
  if (t.includes('gravity') || t.includes('mechanics')) {
    return `
<section class="page">
  <header class="page-header">
    <h1>${title}</h1>
  </header>
  <div class="callout"><strong>Objective:</strong> ${objective}</div>
  
  <p>Gravity is the force by which a planet or other body draws objects toward its center. Isaac Newton formulated the Law of Universal Gravitation:</p>
  
  <div class="math block">
    F = G \\frac{m_1 m_2}{r^2}
  </div>
  
  <div class="grid-2col">
    <div>
      <h3>Orbital Velocity</h3>
      <p>To stay in orbit, an object must travel at a specific speed. This is calculated as:</p>
      <span class="math">v \\approx \\sqrt{\\frac{GM}{r}}</span>
    </div>
    <div class="takeaway">
      Higher orbits require lower velocities to maintain a stable circular path.
    </div>
  </div>

  <div class="diagram">
    graph LR
      Sun((Sun)) --- Mercury
      Sun --- Venus
      Sun --- Earth
      Sun --- Mars
      style Sun fill:#f9d71c,stroke:#333
  </div>
  <p class="figure">Figure 2: Gravitational relationships in the inner solar system.</p>
</section>`.trim();
  }

  // 3. Exercises
  if (type === 'exercise') {
    return `
<section class="page">
  <header class="page-header">
    <h1>${title}</h1>
  </header>
  
  <div class="question">
    <h3>1. Which planet is known as the "Red Planet"?</h3>
    <ol class="mc-options">
      <li class="mc-option">Venus - known for its thick atmosphere.</li>
      <li class="mc-option">Mars - named for its reddish appearance due to iron oxide.</li>
      <li class="mc-option">Jupiter - the largest gas giant.</li>
      <li class="mc-option">Saturn - famous for its extensive ring system.</li>
    </ol>
  </div>

  <div class="question">
    <h3>2. Describe the difference between a terrestrial planet and a gas giant.</h3>
    <div class="answer-box" data-lines="6"></div>
  </div>

  <div class="question">
    <h3>3. Solve the following:</h3>
    <p>If Earth's gravity is <span class="math">1g</span> and Mars' gravity is <span class="math">0.38g</span>, how much would a 100kg astronaut weigh on Mars?</p>
    <div class="answer-line"></div>
  </div>

  <aside class="answer-key" style="display:none">
    <strong>Answer Key:</strong>
    <ol>
      <li>B (Mars)</li>
      <li>Terrestrial planets are rocky and solid; gas giants are primarily composed of hydrogen and helium with no solid surface.</li>
      <li>38kg (100 * 0.38)</li>
    </ol>
  </aside>
</section>`.trim();
  }

  // 4. Case Study
  if (t.includes('case study')) {
    return `
<section class="page">
  <header class="page-header">
    <h1>${title}</h1>
  </header>
  <div class="case-study">
    <h3>The Voyager Golden Record</h3>
    <p>Launched in 1977, the Voyager 1 and 2 spacecraft carry a gold-plated phonograph record containing sounds and images selected to portray the diversity of life and culture on Earth.</p>
    <p>It is intended for any intelligent extraterrestrial life form, or for future humans, who may find it. The record is a "time capsule," intended to communicate a story of our world to extraterrestrials.</p>
    <div class="takeaway">Communication across the cosmos requires a universal language: science and music.</div>
  </div>
  <div class="answer-box" data-lines="4">If you were to add one song to a new Golden Record today, what would it be and why?</div>
</section>`.trim();
  }

  // 5. Glossary
  if (t.includes('glossary')) {
    return `
<section class="page">
  <header class="page-header">
    <h1>${title}</h1>
  </header>
  <dl class="glossary">
    <div class="glossary-item">
      <dt>Astronomical Unit (AU)</dt>
      <dd>The average distance from the Earth to the Sun, approximately 150 million kilometers.</dd>
    </div>
    <div class="glossary-item">
      <dt>Light-Year</dt>
      <dd>The distance light travels in one year, about 9.46 trillion kilometers.</dd>
    </div>
    <div class="glossary-item">
      <dt>Nebula</dt>
      <dd>A giant cloud of dust and gas in space, often the birthplace of stars.</dd>
    </div>
    <div class="glossary-item">
      <dt>Orbit</dt>
      <dd>The curved path of a celestial object or spacecraft around a star, planet, or moon.</dd>
    </div>
  </dl>
</section>`.trim();
  }

  return `
<section class="page">
  <header class="page-header">
    <h1>${title}</h1>
  </header>
  <div class="layout-f">
    <div class="f-top">
      <div class="callout"><strong>Objective:</strong> ${objective}</div>
    </div>
    <div class="f-body">
      <p>Exploring <strong>${title}</strong> using the EduSpark generation engine.</p>
      <div class="grid-2col">
        <div class="bento-main">
          <h3>Factual Overview</h3>
          <p>Standard educational content with Bento-grid layouts.</p>
        </div>
      </div>
    </div>
  </div>
</section>`.trim();
}

export function getDemoConversation(): Conversation {
  const pageSpecs: { title: string; objective: string; type: 'content' | 'exercise' }[] = [
    { title: 'The Grand Design of Our Solar System', objective: 'Overview of the sun and the eight planets.', type: 'content' },
    { title: 'Celestial Mechanics & Gravity', objective: 'Explain orbital motion using Newtonian physics.', type: 'content' },
    { title: 'The Inner Planets', objective: 'Deep dive into Mercury, Venus, Earth, and Mars.', type: 'content' },
    { title: 'Gas Giants & Ice Giants', objective: 'Comparing Jupiter, Saturn, Uranus, and Neptune.', type: 'content' },
    { title: 'Exploration History', objective: 'Timeline of major space missions.', type: 'content' },
    { title: 'Knowledge Check: Planets', objective: 'MCQ and short answer assessment.', type: 'exercise' },
    { title: 'Calculating Planetary Weight', objective: 'Math problems using the gravity formula.', type: 'exercise' },
    { title: 'Case Study: The Voyager Golden Record', objective: 'Analyzing human outreach to the stars.', type: 'content' },
    { title: 'Glossary of Terms', objective: 'Definitions of key astronomical vocabulary.', type: 'content' },
  ];

  const pages: WorkbookPage[] = pageSpecs.map((spec, i) => ({
    id: `demo-page-${i}`,
    title: spec.title,
    type: spec.type,
    content: getMockContent(spec.title, spec.objective, spec.type),
    blocks: [],
    layout: spec.title.includes('Design') ? 'f-pattern' : (spec.title.includes('Gravity') ? 'bento-grid' : 'single-column'),
    theme: 'science-lab'
  }));

  const workbook: Workbook = {
    id: 'demo-wb-solar-system',
    title: 'The Grand Design of Our Solar System',
    subject: 'Astronomy',
    level: 'High School',
    region: 'International',
    pages,
    brandKit: {
      schoolName: 'EduSpark Academy',
      primaryColor: '#CC785C',
      schoolLogo: 'https://img.icons8.com/ios-filled/100/CC785C/star.png'
    },
    stylePrefs: {
      theme: 'scientific-paper',
      questionTypes: ['mcq', 'short-answer', 'math-workspace'],
      density: 'balanced',
      difficulty: 'intermediate',
      accessibility: 'standard'
    }
  };

  return {
    id: 'solar-system-demo-v1',
    title: 'Solar System Demo',
    messages: [
      { role: 'user', text: 'Create a professional workbook about the Solar System.' },
      { role: 'model', text: "I've generated a high-fidelity 9-page workbook on the Solar System for you. This demo showcases Bento grids, KaTeX math, Mermaid diagrams, Case Studies, and a professional Brand Kit." }
    ],
    workbook,
    step: 'complete',
    updatedAt: Date.now()
  };
}
